"use strict";
let favouriteplace = [" Makkah", " USA", " SouthKorea", " Neelum Valley", " New York"];
console.log("original order : " + favouriteplace + "\n");
console.log("Alphabetical order ; " + [...favouriteplace].sort() + "\n");
console.log("original order  ; " + favouriteplace + "\n");
console.log("reverse alphabetical order ;  " + [...favouriteplace].sort().reverse() + "\n");
console.log("original order ; " + favouriteplace + "\n");
console.log("reverse the order of list ; " + favouriteplace.reverse() + "\n");
console.log("reverse the order of list  " + favouriteplace.reverse() + "\n");
console.log("alphabetical order  ; " + favouriteplace.sort() + "\n");
console.log("alphabetical order, reverse  ;" + favouriteplace.sort().reverse() + "\n");
